// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvtpxaojthbojgtkrqfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2dHB4YW9qdGhib2pndGtycWZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MTYyNTUsImV4cCI6MjA2NjI5MjI1NX0._lKVahFpCJqRJZ5LvHMYlsjhFC601u2Z3XLPy51xtZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);